package testDataType;

public class BUSINESS_PARTNER_SETUP_BusinessPartnerTestDataType {
	public String User;
	public String BP_Type;
	public String BP_SubType;
	public String ReferenceType;
	public String ReferenceCodeNumber;
	public String BirthDate;
	public String BirthMonth;
	public String BirthYear;
	public String BirthFullMonth;
	public String Gender;
	public String FirstName;
	public String MiddleName;
	public String LastName;
	public String Profession;
	public String Blacklisted;
	public String KYC_Status;
	public String Remarks;
	public String ID_Type;
	public String ID_Number;
	public String AddressType;
	public String AddressLine1;
	public String AddressLine2;
	public String AddressLine3;
	public String Country;
	public String State;
	public String City;
	public String Zipcode;
	public String ContactType;
	public String ContactPerson;
	public String Designation;
	public String Mobile1;
	public String Phone1;
	public String Email1;
	public String BankName;
	public String BranchName;
	public String AccountType;
	public String AccountNumber;
	public String AccountCurrency;
	public String PaymentAccountIndicator;
	public String AccountStatus;
	public String BankDetailRemark;
	public String HSN_Code;
	public String HSN_CodeRemark;
	public String RemarkByMaker;
}
