package testDataType;

public class ARAP_ARandAPData {

	public String User;
	public String BusinesPartner;
	public String GRN;
	public String GRNStatus;
	public String GRNStatus1;
	public String InvoiceNo;
	public String InvoiceType;
	public String InvoicesubType;
	public String SupplyRefNo;
	public String Discount;
	public String ModeofPayment;
	public String CostCenter;
	public String Remark;
	public String AdjustmentType;
	public String CancelAmount;
	public String branchCode;
	public String gLCode;
	public String Month;
	public String FullMonth;
	public String Year;
	public String Day;
	public String GlMonth;
	public String GlFullMonth;
	public String GlYear;
	public String GlDay;
	public String GlToMonth;
	public String GlFullToMonth;
	public String GlToDate;
	public String PaymentOption;
	public String Partner;
	public String Partner1;
	public String DebitType;
	public String RecivableName;
	public String RecivableName1;
	public String Description;
	public String AdvanceType;
	public String PONumber;
	public String Amount;
	public String BankAcc;
	public String Receiptpayer;
	public String ReceiptRefNo;
	public String ReceiptType;
	public String ReceiptType1;
	public String TxnNo;
	
	public String InvoiceNoBill;
	public String InvoiceNoAuto;
	public String InvoiceTax;
	public String InvoiceRec;
	public String InvoiceImburse;
	public String PanNoReport;
	public String ContractType;
	public String BusinessPartnerName;
	public String HSNCode;
	public String PaymentAmmount;
	public String CreditPeriod;
	public String VendorContractQuantity;
	public String ContractName;
	public String PaymentTerm;
	public String PaymentTermPercentage;
	public String RatePerUnit;
	public String PaymentMode;
	public String GRNItemDetails;
	public String FlatDiscount;
	public String SuplierReferenceNumber;
	public String PanNo;
	public String PanNo1;
	public String AdvNo;
	
}
