Feature: Application Login and verify system generates notification at checker stage

Given Navigate to kubs url and login as maker user
Then select budget menu
And click on the eye icon of supplementary budget sub menu
Then click on add button
And fill the required field for yearly budget type
Then save and submit by maker
Then Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
@Budget_BudgetSupplementary_BP_SB_03_02
Scenario: BP_SB_03_02	To verify system generates notification at checker login
 if maker user creates Supplementory Budgets record and submit the record to checker
Given Navigate to kubs url and login as maker user
Then select budget menu
And click on the eye icon of supplementary budget sub menu
Then click on add button
And fill the required field for yearly budget type
Then save and submit by maker
Then Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 And Find the budget code which is submitted from maker
Then Click on action Button
And Verify the record is generated by opening the record
@Budget_BudgetSupplementary_BP_SB_04_01
Scenario: BP_SB_04_01 To verify whether user is able to reject the Supplementory Budgets
 record where single approval is configured
 Given Navigate to kubs url and login as maker user
Then select budget menu
And click on the eye icon of supplementary budget sub menu
Then click on add button
And fill the required field for yearly budget type
Then save and submit by maker
Then Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click  on action button of record user want to reject
 Then Click  on reject button
 @Budget_BudgetSupplementary_BP_SB_04_04
 Scenario: BP_SB_04_04	If checker user clicks on reject button then record should
  get rejected and Supplementory Budgets record should not get added into the system
  #We cant validate that where rejected record is going as system delete the record
Given Navigate to kubs url and login as maker user
Then select budget menu
And click on the eye icon of supplementary budget sub menu
Then click on add button
And fill the required field for yearly budget type
Then save and submit by maker
Then Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click on action  button of record user want to reject the record.
 Then Click on reject the button.
 @Budget_BudgetSupplementary_BP_SB_06_01
 Scenario: BP_SB_06_01	System should display notification to checker user for approving/rejecting the task or record
 
 Given Navigate to kubs url and login as maker user
Then select budget menu
And click on the eye icon of supplementary budget sub menu
Then click on add button
And fill the required field for yearly budget type
Then save and submit by maker
Then Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click  on action  button of record user want to approv or reject
 @Budget_BudgetSupplementary_BP_SB_06_06
 Scenario: BP_BC_06_06	To verify system prompt the confirmation message post clicking on Return button
Given Navigate to kubs url and login as maker user
Then select budget menu
And click on the eye icon of supplementary budget sub menu
Then click on add button
And fill the required field for yearly budget type
Then save and submit by maker
Then Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click  on  action  button of record user want to Return
 Then Capture  the popup that shows in right corner
 #Below all files are for Budget Supplementary Updation Which is future enhancement
 #Below all files are for Budget Supplementary Updation Which is future enhancement
 #Below all files are for Budget Supplementary Updation Which is future enhancement
 #Below all files are for Budget Supplementary Updation Which is future enhancement 
 @Budget_BudgetSupplementary_BP_SB_15_01
  Scenario: BP_SB_15_01	To verify system generates notification at checker login if 
  maker user updates the details of Supplementory Budgets record and submit the request to checker
 Given Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click   on  action  button of record user want to see the record
  @Budget_BudgetSupplementary_BP_SB_15_02
   Scenario: BP_SB_15_02 To verify checker user is able to select and view the Supplementory Budgets
    record details submitted by maker user
  
 Given Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click on  action  button  of record user want to view
  @Budget_BudgetSupplementary_BP_SB_15_03
   Scenario: BP_SB_15_03 If checker user clicks on approve button then updation request should get approved 
   and all updated details should get saved in system. System should provide the prompt message for 
   verification completed and the data should be save post business validations
 Given Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click on  action  button of record  user want to approve
 Then Click   on approve  button
 
  
  @Budget_BudgetSupplementary_BP_SB_16_01
  
   Scenario: BP_SB_16_01 System should display notification to checker user for approving/rejecting the task or record
 Given Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click on  action  button of record user want  to approve  or reject
   
  @Budget_BudgetSupplementary_BP_SB_16_02 
    Scenario: BP_SB_16_02 If checker user selects the task or notification of Supplementory 
    Budgets record then system should display all data updated by maker user
 Given Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click on  action  button of record user want to view the record
  @Budget_BudgetSupplementary_BP_SB_16_03  
     Scenario: BP_SB_16_03	If checker user clicks on reject button then updation request
      should get rejected and system should not update any details of Supplementory Budgets record
 Given Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click on  action  button of record user want view the record
 Then User click on reject button
 @Budget_BudgetSupplementary_BP_SB_19_01
 Scenario: BP_SB_19_01	System should display notification to checker user for
   approving/rejecting the task or record.
  
 Given Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click on the action  button of record user want to view the record
  @Budget_BudgetSupplementary_BP_SB_19_02
 Scenario:  BP_SB_19_02	If checker user selects the task or notification of Supplementory
   Budgets record then system should display all updated details captured by maker user
 Given Navigate  to URL and login to Checker1
 When Click  on the Security management
 Then Click  on open pool & click clam button
 Then Click  on the Notification
 Then Click on  action  button of the record user want to view the record
 #--------------------------------autoauth----------------tushar---------
   @Budget_BudgetSupplementary_BP_SB_01_04
Scenario: BP_SB_01_04	To verify user is able to create multiple records of Supplementory Budget	
 System should allow user to create multiple records of Supplementory Budget
 Given Navigate to kubs url and login as maker user
Then select budget menu
And click on the eye icon of supplementary budget sub menu
Then click on add button
And fill the required field for yearly budget type

Then Save and aprove the record
Given Navigate to kubs url and login as maker user
Then select budget menu
And click on the eye icon of supplementary budget sub menu
Then click on add button
And fill the required field for yearly budget type

Then Save and aprove the record
  @Budget_BudgetSupplementary_BP_SB_01_02
 Scenario: BP_SB_01_02 If all the mandatory data is captured and user clicks on save button 
 then new Supplementory Budget record should get save.newly added record should get auto approved
 System should display newly created Supplementory Budget detail record in list.
   Given Navigate to kubs url and login as maker user
Then select budget menu
And click on the eye icon of supplementary budget sub menu
Then click on add button
And fill the required field for yearly budget type

Then Save and aprove the record
Then Search the created record
 



  
  
  
  
  